[[redirects]]
  from = "/join"
  to = "https://psychedelicclubofdenver.givingfuel.com/monthly-membership"

[[redirects]]
  from = "/check"
  to = "sms://+17198810768"

[[redirects]]
  from = "/comedy"
  to = "https://www.eventbrite.com/e/718233785587/"

[[redirects]]
  from = "/narcan"
  to = "https://nextdistro.org/resources-collection/narcan-training-video-next-distro"

[[redirects]]
  from = "/fent"
  to = "https://dancesafe.org/wp-content/uploads/2022/11/fentanyl-test-strip-quick-reference-fall-2022-web.jpg"

[[plugins]]
  package = "netlify-plugin-subfont"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
