[[redirects]]
  from = "/join"
  to = "https://psychedelicclubofdenver.givingfuel.com/monthly-membership"

[[redirects]]
  from = "/check"
  to = "sms://+17198810768"

[[redirects]]
  from = "/~1"
  to = "https://www.eventbrite.com/e/psychedelic-club-of-denver-castle-bash-tickets-485569129337"

[[redirects]]
  from = "/tix"
  to = "https://www.eventbrite.com/e/psychedelic-club-of-denver-castle-bash-tickets-485569129337"

[[redirects]]
  from = "/mmsurvey"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSeWt-yVyD807SnIQX3loVxki_Ikt9fSBPVEuzyftYDVIps_-g/viewform"

[[plugins]]
  package = "netlify-plugin-subfont"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
