[[redirects]]
  from = "/join"
  to = "https://psychedelicclubofdenver.givingfuel.com/monthly-membership"

[[plugins]]
  package = "netlify-plugin-subfont"

[[context.production.plugins]]
  package = "@netlify/plugin-lighthouse"

[functions]
  external_node_modules = ["timers/promises"]