[[redirects]]
  from = "/join"
  to = "https://psychedelicclubofdenver.givingfuel.com/monthly-membership"

[[redirects]]
  from = "/check"
  to = "sms://+17198810768"

[[plugins]]
  package = "netlify-plugin-subfont"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
